CREATE DATABASE DB_EXERCICIO_RH;
USE DB_EXERCICIO_RH;

CREATE TABLE TB_COLAB (
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR (255),
FUNCAO VARCHAR (255),
SALARIO DOUBLE,
IDADE INT,
TERCEIRIZADO BOOL,
PRIMARY KEY (ID)
)